version: 0.2
 
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install 
artifacts:
  files:
    - target/Simple-API-0.0.1-SNAPSHOT.jar
  discard-paths: yes